# Generated by Django 4.2.18 on 2025-01-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_inventoryitem_id_alter_survivor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectionreport',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedReports', to='base.survivor'),
        ),
        migrations.AlterField(
            model_name='infectionreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentReports', to='base.survivor'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='base.survivor'),
        ),
    ]
